=begin

rpi-firmware release
--------------------

WORKDIR=workdir.bcm2708 LINUX_DEFCONFIG=bcmrpi_defconfig  rpi-build clean log fbtft_master build

WORKDIR=workdir.bcm2709 LINUX_DEFCONFIG=bcm2709_defconfig rpi-build clean log fbtft_master build

rm -rf workdir; mkdir -p workdir/out
cd workdir && ln -s ../workdir.bcm2709/firmware firmware && cd -
cp workdir.bcm2709/*.{variable,target} workdir/
cp -r workdir.bcm2709/out/* workdir/out/
mv workdir/out/extra/build.log workdir/out/extra/build7.log
cp workdir.bcm2708/out/{*.img,*.dtb,Module.symvers} workdir/out/
cp -r workdir.bcm2708/out/modules/* workdir/out/modules/
cp workdir.bcm2708/out/extra/* workdir.bcm2708/out/extra/.config workdir/out/extra/

rpi-build fbtft_master merge install SSHIP=192.168.10.129


=end

require 'stdlib/rpi-linux'


ENV['COMMIT_MESSAGE'] = "BCM270x_DT: Add interrupt pin to enc28j60-overlay"


# tools are already unpacked
ENV['CROSS_COMPILE'] = '/home/pi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-'


release :fbtft_master => [:rpi_linux_common, :new_release, :spi_bcm2708_dma]


package :new_release do

  Readme.desc { "Raspberry Pi kernel #{VAR['KERNEL_RELEASE']} with SPI DMA support." }
  Readme.body = """
Changelog
---------
#{Time.now.strftime('%Y-%m-%d')}
* FBTFT support is now in raspberrypi/linux.
  This release only adds SPI DMA support on top of that.
* pitft overlay changed name to pitft28-resistive
* These modules are no longer present:
  - gpio_keys_device - [DT overlay example](https://github.com/raspberrypi/linux/blob/rpi-3.18.y/arch/arm/boot/dts/tinylcd35-overlay.dts)
  - ads7846_device - Use ads7846 DT overlay instead. See [/boot/overlays/README](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README)
  - gpio_mouse_device
  - stmpe_device
  - gpio_backlight_device
  - rpi_power_switch
  - spi-config
* Builtin console fonts are not enabled (fbcon=font:XX).
  - [sudo dpkg-reconfigure console-setup](https://github.com/notro/fbtft/wiki/Boot-console#console-font)
* Other kconfig options no longer enabled:
  - MOUSE_GPIO
  - GPIO_MCP23S08
  - DYNAMIC_DEBUG

2015-02-07
* Pi 2 support

2014-12-07
* [fbtft_device: added support for waveshare32b](https://github.com/notro/fbtft/commit/e67014490a9df34b9a4bf04e49c50254aebc10a8)
* [fbtft_device: add Tontec 3.5 support](https://github.com/notro/fbtft/commit/8116d7273be8816ce70c1a017b4466ae17e27d53)
* [fb_ili9481,6: regwidth was incorrect](https://github.com/notro/fbtft/commit/c92097b5a5ef82e298a4fe8ec7859c9378e435d8)
* [fbtft: make it possible to override regwidth](https://github.com/notro/fbtft/commit/566dca0e9d531b54c11ea9aea47f76695472776c)

"""

  target :build do
    cp Rake.application.rakefile, workdir('out/extra/')
  end
end

# DMA capable SPI master driver
package :spi_bcm2708_dma do
  github_tarball 'notro/spi-bcm2708', 'spi-bcm2708-dma'

  target :patch do
    sh "cp #{workdir('spi-bcm2708-dma/spi-bcm2708.c')} #{workdir('linux/drivers/spi')}"
  end
end
